import { AntdRegistry } from "@ant-design/nextjs-registry";
import { App, ConfigProvider } from "antd";
import type { Metadata } from "next";
import localFont from "next/font/local";

import ptBR from "antd/locale/pt_BR";
import "dayjs/locale/pt-br";

import "./globals.css";
import dayjs from "dayjs";

dayjs.locale("pt-br");

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<AntdRegistry layer>
					<ConfigProvider locale={ptBR}>
						<App className="flex w-full h-full">{children}</App>
					</ConfigProvider>
				</AntdRegistry>
			</body>
		</html>
	);
}
